version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mypassword
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
